# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.1.1
      name: Build with aarch64
      id: build
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        setup: |
          mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
        install: |
          apt update -y
          apt install default-jdk maven build-essential gcc gawk -y
        run: |
          mvn -B -am -pl plugins/linux/ clean compile
          mv ./plugins/linux/target/natives/*.so /artifacts/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: ./artifacts
